# Generated by Django 3.2.3 on 2021-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210602_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='End_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
