# Generated by Django 3.2.3 on 2021-06-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210602_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='End_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='Start_date',
        ),
    ]
