# Generated by Django 3.2.3 on 2021-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210602_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='End_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='Start_date',
            field=models.DateField(null=True),
        ),
    ]
