# Generated by Django 3.2.3 on 2021-06-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210602_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='End_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
