# Generated by Django 3.2.3 on 2021-06-02 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210602_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=400)),
                ('featured_image', models.ImageField(blank=True, upload_to='covers/')),
                ('Latitude', models.CharField(max_length=200)),
                ('Google_maps_link', models.CharField(max_length=200)),
                ('Plus_code', models.CharField(max_length=200)),
                ('ASSETS_TYPE', models.CharField(choices=[('IOS', 'IOS'), ('ANDROID', 'Android')], default='IOS', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Google_maps_link', models.CharField(max_length=200)),
                ('Plus_code', models.CharField(max_length=200)),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='events.assets')),
            ],
        ),
    ]
