# Generated by Django 3.2.3 on 2021-06-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_assets_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
