# Generated by Django 3.2.3 on 2021-06-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
