# Generated by Django 3.2.3 on 2021-06-02 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Google_maps_link', models.CharField(max_length=200)),
                ('Plus_code', models.CharField(max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Asset', to='event.asset')),
            ],
        ),
    ]
