# Generated by Django 3.2.3 on 2021-06-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ending_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starting_date',
            field=models.DateField(null=True),
        ),
    ]
