# Generated by Django 3.2.3 on 2021-06-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210602_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Plus_code',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Longitude',
        ),
    ]
