# Generated by Django 3.2.3 on 2021-06-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210605_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Latitude',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='Longitude',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
