# Generated by Django 3.2.3 on 2021-06-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20210605_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Radius',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
