# Generated by Django 3.2.3 on 2021-06-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20210605_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='event.location'),
        ),
    ]
