# Generated by Django 3.2.3 on 2021-06-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Locations',
        ),
    ]
