# Generated by Django 3.2.3 on 2021-06-05 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_event_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='event.location'),
        ),
    ]
