# Generated by Django 3.2.3 on 2021-06-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_event_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='Asset11', to='event.asset'),
            preserve_default='true',
        ),
    ]
