# Generated by Django 3.2.3 on 2021-06-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20210606_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Locations',
        ),
        migrations.RemoveField(
            model_name='event',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='Events',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, related_name='Asset_Events', to='event.event'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='location',
            name='Events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='event.event'),
        ),
    ]
