# Generated by Django 3.2.3 on 2021-06-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20210606_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Events',
        ),
    ]
