# Generated by Django 3.2.3 on 2021-06-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_remove_asset_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Events',
        ),
        migrations.AddField(
            model_name='event',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_Location', to='event.location'),
        ),
    ]
