# Generated by Django 3.2.3 on 2021-06-24 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0020_auto_20210606_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='ASSETS_TYPE',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Google_maps_link',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Locations',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='code',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Events',
        ),
        migrations.AddField(
            model_name='asset',
            name='Asset_File',
            field=models.FileField(blank=True, upload_to='Assets/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Assets',
            field=models.ManyToManyField(to='event.Asset'),
        ),
        migrations.AddField(
            model_name='event',
            name='Locations',
            field=models.ManyToManyField(to='event.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='location',
            name='Assets',
            field=models.ManyToManyField(to='event.Asset'),
        ),
        migrations.AddField(
            model_name='location',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
