# Generated by Django 3.2.3 on 2021-06-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20210606_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Events',
        ),
        migrations.AddField(
            model_name='location',
            name='Events',
            field=models.ManyToManyField(to='event.Event'),
        ),
    ]
