# Generated by Django 3.2.3 on 2021-06-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20210606_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Events',
        ),
        migrations.AddField(
            model_name='event',
            name='Locations',
            field=models.ManyToManyField(to='event.Location'),
        ),
    ]
