# Generated by Django 3.2.3 on 2021-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20210606_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Locations',
        ),
        migrations.AddField(
            model_name='location',
            name='Assets',
            field=models.ManyToManyField(to='event.Asset'),
        ),
    ]
