# Generated by Django 3.2.3 on 2021-06-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20210626_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='Latitude',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Longitude',
            field=models.CharField(max_length=255),
        ),
    ]
