# Generated by Django 3.2.3 on 2021-06-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_event_assets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
