# Generated by Django 3.2.3 on 2021-06-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
