# Generated by Django 3.2.3 on 2021-06-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_alter_event_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Assets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Locations',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Assets',
        ),
    ]
