# Generated by Django 3.2.3 on 2021-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_auto_20210609_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Assets',
            field=models.ManyToManyField(to='event.Asset'),
        ),
        migrations.AddField(
            model_name='event',
            name='Locations',
            field=models.ManyToManyField(to='event.Location'),
        ),
    ]
