# Generated by Django 3.2.3 on 2021-06-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_auto_20210609_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Assets',
            field=models.ManyToManyField(to='event.Asset'),
        ),
    ]
