# Generated by Django 3.2.3 on 2021-06-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_auto_20210613_1044'),
        ('event', '0031_event_qr_code'),
    ]

    operations = [
    ]
