# Generated by Django 3.2.3 on 2021-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_merge_0031_auto_20210613_1044_0031_event_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='code',
        ),
        migrations.AddField(
            model_name='asset',
            name='Asset_File',
            field=models.FileField(blank=True, max_length=400, upload_to='Assets/'),
        ),
        migrations.AddField(
            model_name='location',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
