# Generated by Django 3.2.3 on 2021-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_auto_20210615_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='ASSETS_TYPE',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Google_maps_link',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='asset',
            name='Latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='Longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
