# Generated by Django 3.2.3 on 2021-06-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_auto_20210621_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
