# Generated by Django 3.2.3 on 2021-07-11 10:11

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0035_auto_20210622_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Asset_File',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Longitude',
        ),
        migrations.AddField(
            model_name='asset',
            name='Multi_Locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None), null=True, size=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='multi_uploads',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='covers/'), null=True, size=None),
        ),
        migrations.AddField(
            model_name='asset',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
